### ISSUE TITLE
Similar Project 

### ISSUE THREAD

**Issue by salamanders** [Beepiz/CameraCoroutines#4]
I too didn't enjoy camera2 callbacks, and made
https://github.com/salamanders/deconstructed-camera/blob/master/mobile/app/src/main/java/info/benjaminhill/deconcamera/EZCam.kt

Glad to see I'm not the only one attempting to tackle this!  Will go through this project, see if I can borrow any good ideas.

**Comment by LouisCAD** [comment]
I'm closing this issue as it is not really an issue, but that doesn't mean I'm closing the discussion.
Glad to see I'm not the only one too! :)

**Comment by salamanders** [comment]
Would GREATLY appreciate any suggestions you may have.  I've already started using things like `RequiresPermission`

**Comment by LouisCAD** [comment]
My suggestion would be to consider contributing here on this repo instead 😉 
As you can see, the Camera2 API is not fully covered yet, and the sample could be improved.
